### ISSUE TITLE
CodeRedLib object: True/False instead of original value

### ISSUE THREAD

**Issue by padremayi** [lducas/CodeRed#1]
I hava an **np.array(matrix)** array with a large integer inside. When I use

`red = CodeRedLib(np.array(matrix)) `

I got an object with True and False instead of original Numpy values, why? I can't use

**np.array(matrix, dtype="int64")**

because I got an overflow error:

`OverflowError: Python int too large to convert to C long`

**Comment by lducas** [comment]
Because this library is about binary codes, hence the input basis should be boolean (aka over the field F_2)
